language: node_js
node_js:
  - "0.10"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "31.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/releases/0.9.1/slimerjs-0.9.1.zip"
  - "unzip slimerjs-0.9.1.zip"
  - "mv slimerjs-0.9.1 ./slimerjs"
  - npm install -g casperjs
script:
  - casperjs
  - cd java && make && cd ..
  - cd tests && make && cd ..
